 Data Wrangling, I

Perform the following operations using Python on any open source dataset (e.g., data.csv)

1. Import all the required Python Libraries.

2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear  
            description of the data and its source (i.e., URL of the web site).

3. Load the Dataset into pandas dataframe.

4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.

5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.

6. Turn categorical variables into quantitative variables in Python.

In addition to the codes and outputs, explain every operation that you do in the above steps and
explain everything that you do to import/read/scrape the data set

In [ ]:
1

In [1]:
import numpy as np;

In [3]:
import pandas as pd;

In [4]:
df = pd.read_csv("/content/sample_data/Student_Performance.csv");

In [5]:
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0
4,male,group C,some college,standard,none,76.0,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0
998,female,group D,some college,standard,completed,68.0,78.0,77.0
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0

3

In [6]:
print(df.isnull());

     gender  race/ethnicity  parental_level_of_education  lunch  \
0     False           False                        False  False
1     False           False                        False  False
2     False           False                        False  False
3     False           False                        False  False
4     False           False                        False  False
..      ...             ...                          ...    ...
995   False           False                        False  False
996   False           False                        False  False
997   False           False                        False  False
998   False           False                        False  False
999   False           False                        False  False

     test_preparation_course  math_score  reading_score  writing_score
0                      False       False          False          False
1                      False       False          False          False
2                      False       False          False          False
3                      False       False          False          False
4                      False       False          False          False
..                       ...         ...            ...            ...
995                    False       False          False          False
996                    False       False          False          False
997                    False       False          False          False
998                    False       False          False          False
999                    False       False          False          False

[1000 rows x 8 columns]

In [7]:
print(df.isnull().sum());

gender                         0
race/ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     2
reading_score                  4
writing_score                  2
dtype: int64

In [11]:
df =df.dropna();

In [12]:
print(df.isnull().sum());

gender                         0
race/ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [13]:
print(df.describe());

       math_score  reading_score  writing_score
count  992.000000     992.000000     992.000000
mean    66.115927      69.178427      68.076613
std     15.168335      14.645265      15.237050
min      0.000000      17.000000      10.000000
25%     57.000000      59.000000      57.000000
50%     66.000000      70.000000      69.000000
75%     77.000000      79.250000      79.000000
max    100.000000     100.000000     100.000000

In [14]:
print(df.shape);

(992, 8)

In [15]:
5

5

In [16]:
print(df.info);

<bound method DataFrame.info of      gender race/ethnicity parental_level_of_education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test_preparation_course  math_score  reading_score  writing_score
0                      none        72.0           72.0           74.0
1                 completed        69.0           90.0           88.0
2                      none        90.0           95.0           93.0
3                      none        47.0           57.0           44.0
4                      none        76.0           78.0           75.0
..                      ...         ...            ...            ...
995               completed        88.0           99.0           95.0
996                    none        62.0           55.0           55.0
997               completed        59.0           71.0           65.0
998               completed        68.0           78.0           77.0
999                    none        77.0           86.0           86.0

[992 rows x 8 columns]>

In [28]:
df["math_score"] = df["math_score"].astype(int)

/tmp/ipykernel_1275/4273663124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["math_score"] = df["math_score"].astype(int)

In [29]:
print(df["math_score"]);

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 992, dtype: int64

6

In [30]:
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72.0,74.0
1,female,group C,some college,standard,completed,69,90.0,88.0
2,female,group B,master's degree,standard,none,90,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44.0
4,male,group C,some college,standard,none,76,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99.0,95.0
996,male,group C,high school,free/reduced,none,62,55.0,55.0
997,female,group C,high school,free/reduced,completed,59,71.0,65.0
998,female,group D,some college,standard,completed,68,78.0,77.0
999,female,group D,some college,free/reduced,none,77,86.0,86.0

In [31]:
df["gender"]= df["gender"].replace({'female':0, 'male':1});

/tmp/ipykernel_1275/2771123102.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["gender"]= df["gender"].replace({'female':0, 'male':1});
/tmp/ipykernel_1275/2771123102.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gender"]= df["gender"].replace({'female':0, 'male':1});

In [32]:
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,0,group B,bachelor's degree,standard,none,72,72.0,74.0
1,0,group C,some college,standard,completed,69,90.0,88.0
2,0,group B,master's degree,standard,none,90,95.0,93.0
3,1,group A,associate's degree,free/reduced,none,47,57.0,44.0
4,1,group C,some college,standard,none,76,78.0,75.0
...,...,...,...,...,...,...,...,...
995,0,group E,master's degree,standard,completed,88,99.0,95.0
996,1,group C,high school,free/reduced,none,62,55.0,55.0
997,0,group C,high school,free/reduced,completed,59,71.0,65.0
998,0,group D,some college,standard,completed,68,78.0,77.0
999,0,group D,some college,free/reduced,none,77,86.0,86.0