<a href="https://colab.research.google.com/github/HarshalSawale4/DSBDA-Practical/blob/main/Practicle3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Descriptive Statistics - Measures of Central Tendency and variability
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.  
2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.

 Provide the codes with outputs and explain everything that you do in this step.

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/iris.csv")

In [ ]:
df

     sepallength  sepalwidth  petallength  petalwidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.describe()

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [ ]:
df["sepallength"].mean()

np.float64(5.843333333333334)

In [ ]:
df["sepallength"].median()

5.8

In [ ]:
df["sepallength"].min()

4.3

In [ ]:
df["sepallength"].max()

7.9

In [ ]:
df["sepallength"].std()

0.8280661279778629

In [ ]:
df["sepalwidth"].mean()

np.float64(3.0540000000000003)

In [ ]:
df["sepalwidth"].median()

3.0

In [ ]:
df["sepalwidth"].min()

2.0

In [ ]:
df["sepalwidth"].max()

4.4

In [ ]:
df["sepalwidth"].std()

0.4335943113621737

In [ ]:
df["petallength"].describe()

count    150.000000
mean       3.758667
std        1.764420
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: petallength, dtype: float64

In [ ]:
df["petallength"].mean()

np.float64(3.758666666666666)

In [ ]:
df["petallength"].min()

1.0

In [ ]:
df["petallength"].max()

6.9

In [ ]:
df["petallength"].std()

1.7644204199522617

In [ ]:
df["petalwidth"].describe()

count    150.000000
mean       1.198667
std        0.763161
min        0.100000
25%        0.300000
50%        1.300000
75%        1.800000
max        2.500000
Name: petalwidth, dtype: float64

In [ ]:
df["petalwidth"].mean()

np.float64(1.1986666666666668)

In [ ]:
df["petalwidth"].min()

0.1

In [ ]:
df["petalwidth"].max()

2.5

In [ ]:
df["petalwidth"].std()

0.7631607417008414

statement  2

In [ ]:
df.groupby('species').describe()

                sepallength                                              \
                      count   mean       std  min    25%  50%  75%  max
species
Iris-setosa            50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor        50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica         50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepalwidth         ... petallength      petalwidth         \
                     count   mean  ...         75%  max      count   mean
species                            ...
Iris-setosa           50.0  3.418  ...       1.575  1.9       50.0  0.244
Iris-versicolor       50.0  2.770  ...       4.600  5.1       50.0  1.326
Iris-virginica        50.0  2.974  ...       5.875  6.9       50.0  2.026


                      std  min  25%  50%  75%  max
species
Iris-setosa      0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [ ]:
df.groupby("species").describe().sum()

sepallength  count    150.000000
             mean      17.530000
             std        1.504540
             min       14.100000
             25%       16.625000
             50%       17.400000
             75%       18.400000
             max       20.700000
sepalwidth   count    150.000000
             mean       9.162000
             std        1.017319
             min        6.500000
             25%        8.450000
             50%        9.200000
             75%        9.850000
             max       11.600000
petallength  count    150.000000
             mean      11.276000
             std        1.195317
             min        8.500000
             25%       10.500000
             50%       11.400000
             75%       12.050000
             max       13.900000
petalwidth   count    150.000000
             mean       3.596000
             std        0.579612
             min        2.500000
             25%        3.200000
             50%        3.500000
             75%        4.100000
             max        4.900000
dtype: float64